id = '/home/malkaviel/Documents/projects/intellij/maskerad_level_parser/data_serialization_test/gameobject5.toml'

[transform]
position = [
    5.0,
    7.0,
    11.0,
]
rotation = [
    0.8,
    5.2,
    1.0,
]
scale = [
    2.4,
    2.2,
    2.9,
]
